if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $HOME/.zprezto/runcoms/zshrc

export ZSH="/home/likono/.oh-my-zsh"

export LANG=en_US.UTF-8

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
  export EDITOR='mvim'
fi

export ARCHFLAGS="-arch x86_64"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:`pwd`/flutter/bin"

for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file
CASE_SENSITIVE="true"

source /home/linuxbrew/.linuxbrew/opt/powerlevel10k/powerlevel10k.zsh-theme


plugins=(docker git zsh-autosuggestions dotenv npm ls zsh-syntax-highlighting colored-man-pages kubectl history emoji encode64 sudo web-search copydir copyfile copybuffer jsontools)

alias l='ll'
alias src='source ~/.zshrc'
alias msrc='v ~/.zshrc'
alias v='vim'
alias vi='vim'
alias stmux='tmux new -s $1'
alias dclean='~/clean-docker.sh'


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


source $ZSH/oh-my-zsh.sh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"


export NVM_DIR="$HOME/.nvm"
  [ -s "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh" ] && . "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm"


dcup() {
  docker compose -f "$1" up
}

gitall() {
    git add .
    if [ "$1" != "" ] # or better, if [ -n "$1" ]
    then
        git commit -m "$1"
    else
        git commit -m update
    fi
    git push
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias pbcopys='xsel --clipboard --input'
alias pbpastes='xsel --clipboard --output'
alias python='python3'
alias pip='pip3'

